### ISSUE TITLE
create open API

### ISSUE THREAD

**Issue by Anti-Gen** [kelompok-2-immarsive/Project_BE#2]

**Comment by Anti-Gen** [comment]
buat dokumentasi API

**Comment by Anti-Gen** [comment]
https://app.swaggerhub.com/apis-docs/Anti-Gen/PROJCECT-BE13/1.0.0
link dokumentasi

**Comment by mitro-ubaidillah** [comment]
okee mas, sudah sesuai untuk api nya
terima kasih
